sudo: false
services:
  - docker
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "pypy"
env:
  - GROUP=unit
  - GROUP=integration
  - GROUP=system
  - GROUP=performance
if: tag IS blank
matrix:
  allow_failures:
    - env: GROUP=performance
install: pip install codecov tox-travis
script: ./ci/run-tests.sh
after_success: codecov
